server:
  port: 8080

spring:
  application:
    name: hana-ieum-server
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update # create-drop, update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul

# 디버그 로깅 활성화
logging:
  level:
    root: INFO
    org.springframework: DEBUG
    org.hibernate: DEBUG
    com.hanaieum: DEBUG

jwt:
  secret: ${JWT_SECRET:temp-jwt-secret-key-for-development-12345678901234567890123456789012}
  access-expiration: ${JWT_ACCESS_EXPIRATION:3600000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}

solapi:
  api-key: ${SOLAPI_API_KEY:}
  api-secret: ${SOLAPI_API_SECRET:}
  sender: ${SOLAPI_SENDER:}

# Springdoc OpenAPI 설정
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true